version = 0.1
[default.deploy.parameters]
stack_name = "web-sockets-try"
resolve_s3 = true
s3_prefix = "web-sockets-try"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"simplechat_connections\""
image_repositories = []
